/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import { FileUploadResponse } from "../redux/data-types/message"; 

export interface paths {
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Basic health check endpoint.
         */
        get: operations["health_check_api_v1_health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detailed Health Check
         * @description Detailed health check with system information.
         */
        get: operations["detailed_health_check_api_v1_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Kubernetes-style readiness probe.
         */
        get: operations["readiness_check_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Check
         * @description Kubernetes-style liveness probe.
         */
        get: operations["liveness_check_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Framework Request
         * @description Process a framework request from the frontend chat.
         *     This is the main endpoint that receives user messages and routes them to the supervisor.
         */
        post: operations["process_framework_request_framework_process_post"];
        delete?: never;
        /**
         * Process Options
         * @description Handle CORS preflight requests for the process endpoint.
         */
        options: operations["process_options_framework_process_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/user_input/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To User Input
         * @description Respond to a user input request.
         */
        post: operations["respond_to_user_input_framework_user_input_respond_post"];
        delete?: never;
        /**
         * User Input Options
         * @description Handle CORS preflight requests for the user input endpoint.
         */
        options: operations["user_input_options_framework_user_input_respond_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send a message in the chat interface.
         *     Creates a new conversation or continues an existing one.
         *     Integrates with the multi-agent task system.
         */
        post: operations["send_message_framework_messages_post"];
        delete?: never;
        /**
         * Messages Options
         * @description Handle CORS preflight for messages endpoint.
         */
        options: operations["messages_options_framework_messages_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/conversations/{conversation_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation History
         * @description Get conversation message history.
         */
        get: operations["get_conversation_history_framework_conversations__conversation_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        /**
         * Conversation History Options
         * @description Handle CORS preflight for conversation history endpoint.
         */
        options: operations["conversation_history_options_framework_conversations__conversation_id__history_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Conversations
         * @description Get all conversations for a user.
         */
        get: operations["get_user_conversations_framework_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        /**
         * Conversations Options
         * @description Handle CORS preflight for conversations endpoint.
         */
        options: operations["conversations_options_framework_conversations_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/conversations/{conversation_id}/user_input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond To Conversation User Input
         * @description Respond to user input requests within a conversation context.
         */
        post: operations["respond_to_conversation_user_input_framework_conversations__conversation_id__user_input_post"];
        delete?: never;
        /**
         * Conversation User Input Options
         * @description Handle CORS preflight for conversation user input endpoint.
         */
        options: operations["conversation_user_input_options_framework_conversations__conversation_id__user_input_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/framework/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Framework Status
         * @description Get current framework status and statistics.
         */
        get: operations["get_framework_status_framework_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        /**
         * Status Options
         * @description Handle CORS preflight for status endpoint.
         */
        options: operations["status_options_framework_status_options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send a message to the multi-agent system.
         *
         *     Two modes:
         *     1. New task (no task_id): Create new supervisor and return system response
         *     2. Continue task (with task_id): Continue existing task with user input - task_id becomes parent for all operations
         */
        post: operations["send_message_api_v1_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core-agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Core Agent
         * @description Chat directly with the CoreBusinessAgent with streaming support
         *     Implements parent task ID approach for conversation management
         */
        post: operations["chat_with_core_agent_api_v1_core_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core-agent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Core Agent Status
         * @description Get the status of the CoreBusinessAgent
         */
        get: operations["get_core_agent_status_api_v1_core_agent_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core-agent/conversation/{parent_task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation History
         * @description Get conversation history using parent task ID
         *     Returns all tasks and messages in a conversation
         */
        get: operations["get_conversation_history_api_v1_core_agent_conversation__parent_task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core-agent/conversations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Conversations
         * @description Get all conversations (parent tasks) for a user
         */
        get: operations["get_user_conversations_api_v1_core_agent_conversations__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List all available agents.
         */
        get: operations["list_agents_api_v1_agents__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Get details for a specific agent.
         */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Tasks
         * @description Get all tasks with pagination and filtering options.
         *
         *     - **page**: Page number (starts from 1)
         *     - **page_size**: Number of tasks per page (max 1000)
         *     - **status_filter**: Filter by task status (CREATED, IN_PROGRESS, WAITING, COMPLETED, FAILED, CANCELLED)
         *     - **user_id**: Filter by user ID
         *     - **parent_only**: If true, only return tasks that have no parent (top-level tasks)
         */
        get: operations["get_all_tasks_api_v1_tasks__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Detail
         * @description Get detailed information about a specific task including all associated messages.
         *
         *     **Special Logic for Messages:**
         *     - If the task has a parent_id, returns ALL messages where task_id = parent_id
         *     - If the task has no parent, returns messages where task_id = this task's id
         *     - This ensures proper message grouping for parent-child task relationships
         *
         *     **Includes (all sorted by timestamp):**
         *     - Task details (request, status, actors, etc.)
         *     - All related messages (chronological order by timestamp)
         *     - Status change history (chronological order by timestamp)
         *     - Task results (chronological order by timestamp)
         *     - Child tasks (chronological order by created_at)
         */
        get: operations["get_task_detail_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/editable-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Editable Resources
         * @description Get all editable resources (email drafts, CRM records, calendar events) for a task.
         */
        get: operations["get_task_editable_resources_api_v1_tasks__task_id__editable_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/editable-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Editable Resources
         * @description Get all editable resources across all tasks.
         */
        get: operations["get_all_editable_resources_api_v1_tasks_editable_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Integrations
         * @description List all available integrations and their status.
         */
        get: operations["list_integrations_api_v1_integrations__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/{integration_name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Integration Status
         * @description Get detailed status for a specific integration.
         */
        get: operations["get_integration_status_api_v1_integrations__integration_name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/{integration_name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Integration
         * @description Test connection to a specific integration.
         */
        post: operations["test_integration_api_v1_integrations__integration_name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Emails
         * @description List emails.
         */
        get: operations["list_emails_api_v1_emails__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calendar Integrations
         * @description Get connected calendar providers.
         */
        get: operations["get_calendar_integrations_api_v1_calendar_integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Calendar Provider
         * @description Connect to calendar provider using OAuth.
         */
        post: operations["connect_calendar_provider_api_v1_calendar_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/disconnect/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect Calendar Provider
         * @description Disconnect calendar provider.
         */
        delete: operations["disconnect_calendar_provider_api_v1_calendar_disconnect__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Calendar Data
         * @description Sync calendar data from all connected providers.
         */
        post: operations["sync_calendar_data_api_v1_calendar_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meetings
         * @description Get meetings with optional filters.
         */
        get: operations["get_meetings_api_v1_calendar_meetings_get"];
        put?: never;
        /**
         * Create Meeting
         * @description Create a new meeting.
         */
        post: operations["create_meeting_api_v1_calendar_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meeting
         * @description Get specific meeting by ID.
         */
        get: operations["get_meeting_api_v1_calendar_meetings__meeting_id__get"];
        /**
         * Update Meeting
         * @description Update an existing meeting.
         */
        put: operations["update_meeting_api_v1_calendar_meetings__meeting_id__put"];
        post?: never;
        /**
         * Delete Meeting
         * @description Delete a meeting.
         */
        delete: operations["delete_meeting_api_v1_calendar_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/meetings/{meeting_id}/recap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meeting Recap
         * @description Get meeting recap/notes.
         */
        get: operations["get_meeting_recap_api_v1_calendar_meetings__meeting_id__recap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Meeting Recap Status
         * @description Update meeting recap status.
         */
        patch: operations["update_meeting_recap_status_api_v1_calendar_meetings__meeting_id__recap_patch"];
        trace?: never;
    };
    "/api/v1/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List documents.
         */
        get: operations["list_documents_api_v1_documents__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description List workflow templates.
         */
        get: operations["list_workflows_api_v1_workflows__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Get analytics data.
         */
        get: operations["get_analytics_api_v1_analytics__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description API root endpoint with basic information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Info
         * @description API version information and available endpoints.
         */
        get: operations["api_info_api_v1_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalendarProvider
         * @description Calendar provider information.
         */
        CalendarProvider: {
            /**
             * Provider
             * @description Provider name (google, outlook, apple)
             */
            provider: string;
            /**
             * Display Name
             * @description Human-readable provider name
             */
            display_name: string;
            /**
             * Connected
             * @description Whether provider is connected
             */
            connected: boolean;
            /**
             * Email
             * @description Connected account email
             */
            email?: string | null;
            /**
             * Last Sync
             * @description Last sync timestamp
             */
            last_sync?: string | null;
            /**
             * Sync Status
             * @description Sync status (active, error, pending)
             */
            sync_status: string;
        };
        /**
         * ChatMessage
         * @description Chat message model for the messaging endpoint.
         */
        ChatMessage: {
            /**
             * Content
             * @description Message content
             */
            content: string;
            /**
             * User Id
             * @description User identifier
             * @default web_user
             */
            user_id: string;
            /**
             * Conversation Id
             * @description Conversation ID to continue existing chat
             */
            conversation_id?: string | null;
            /**
             * Message Type
             * @description Type of message: user, system, agent
             * @default user
             */
            message_type: string;
            /**
             * Context
             * @description Additional context
             */
            context?: Record<string, never> | null;
        };
        /**
         * ChatResponse
         * @description Response model for chat messages.
         */
        ChatResponse: {
            /** Success */
            success: boolean;
            /** Message Id */
            message_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Task Id */
            task_id?: string | null;
            /** Response */
            response?: string | null;
            /**
             * Status
             * @description Message status
             * @default received
             */
            status: string;
            /** Data */
            data?: Record<string, never> | null;
        };
        /**
         * ConnectProviderRequest
         * @description Request model for connecting calendar provider.
         */
        ConnectProviderRequest: {
            /**
             * Provider
             * @description Provider name (google, outlook, apple)
             */
            provider: string;
            /**
             * Auth Code
             * @description OAuth authorization code
             */
            auth_code?: string | null;
            /**
             * Redirect Uri
             * @description OAuth redirect URI
             */
            redirect_uri?: string | null;
        };
        /** CoreAgentRequest */
        CoreAgentRequest: {
            /** Content */
            content: string;
            /**
             * User Id
             * @default test@rialto-financial.com
             */
            user_id: string;
            /** Continue Task Id */
            continue_task_id?: string | null;
            /**
             * Enable Streaming
             * @default true
             */
            enable_streaming?: boolean | null;
            /** Files */
            files?: FileUploadResponse[] | null;
            /** File Count */
            fileCount?: number | null;
            /** Has Files */
            hasFiles?: boolean | null;
        };
        /** CoreAgentResponse */
        CoreAgentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
        };
        /**
         * CreateMeetingRequest
         * @description Request model for creating a new meeting.
         */
        CreateMeetingRequest: {
            /**
             * Title
             * @description Meeting title
             */
            title: string;
            /**
             * Description
             * @description Meeting description
             */
            description?: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Meeting start time (ISO 8601)
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             * @description Meeting end time (ISO 8601)
             */
            end_time: string;
            /**
             * Attendees
             * @description List of attendee names/emails
             * @default []
             */
            attendees: string[];
            /**
             * Location
             * @description Meeting location
             */
            location?: string | null;
            /**
             * Meeting Url
             * @description Virtual meeting URL
             */
            meeting_url?: string | null;
            /**
             * Calendar Provider
             * @description Calendar provider
             * @default google
             */
            calendar_provider: string;
            /**
             * Client Meeting
             * @description Whether this is a client meeting
             * @default false
             */
            client_meeting: boolean;
        };
        /**
         * EditableResource
         * @description Model for editable resources (emails, CRM records, calendar events)
         */
        EditableResource: {
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string;
            /** Title */
            title: string;
            /** Edit Url */
            edit_url: string;
            /** View Url */
            view_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Task Id */
            task_id: string;
            /** Agent Name */
            agent_name: string;
        };
        /**
         * FrameworkRequest
         * @description Request model for framework processing.
         */
        FrameworkRequest: {
            /**
             * Request
             * @description User request to process
             */
            request: string;
            /**
             * User Id
             * @description User identifier
             * @default web_user
             */
            user_id: string;
            /**
             * Context
             * @description Additional context
             */
            context?: Record<string, never> | null;
        };
        /**
         * FrameworkResponse
         * @description Response model for framework processing.
         */
        FrameworkResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Data */
            data?: Record<string, never> | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Meeting
         * @description Meeting object with all details.
         */
        Meeting: {
            /**
             * Id
             * @description Unique meeting identifier
             */
            id: string;
            /**
             * Title
             * @description Meeting title
             */
            title: string;
            /**
             * Description
             * @description Meeting description
             */
            description?: string | null;
            /**
             * Start Time
             * Format: date-time
             * @description Meeting start time (ISO 8601)
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             * @description Meeting end time (ISO 8601)
             */
            end_time: string;
            /**
             * Attendees
             * @description List of attendee names/emails
             * @default []
             */
            attendees: string[];
            /**
             * Location
             * @description Meeting location
             */
            location?: string | null;
            /**
             * Meeting Url
             * @description Virtual meeting URL
             */
            meeting_url?: string | null;
            /**
             * Calendar Provider
             * @description Calendar provider (google, outlook, apple)
             */
            calendar_provider: string;
            /**
             * Status
             * @description Meeting status
             * @default scheduled
             */
            status: string;
            /**
             * Has Recap
             * @description Whether meeting has recap/notes
             * @default false
             */
            has_recap: boolean;
            /**
             * Client Meeting
             * @description Whether this is a client meeting
             * @default false
             */
            client_meeting: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * MeetingRecap
         * @description Meeting recap/notes information.
         */
        MeetingRecap: {
            /**
             * Meeting Id
             * @description Meeting ID
             */
            meeting_id: string;
            /**
             * Recap Text
             * @description Meeting recap/notes
             */
            recap_text: string;
            /**
             * Key Points
             * @description Key discussion points
             * @default []
             */
            key_points: string[];
            /**
             * Action Items
             * @description Action items from meeting
             * @default []
             */
            action_items: string[];
            /**
             * Next Steps
             * @description Next steps
             * @default []
             */
            next_steps: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** MessageDetail */
        MessageDetail: {
            /** Id */
            id: string;
            /** Message Type */
            message_type: string;
            /** Content */
            content: string;
            /** Role */
            role?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** User Id */
            user_id?: string | null;
            /** Account */
            account?: string | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
        };
        /** MessageRequest */
        MessageRequest: {
            /** Content */
            content: string;
            /**
             * User Id
             * @default test@rialto-financial.com
             */
            user_id: string;
            /** Task Id */
            task_id?: string | null;
            /**
             * Enable Streaming
             * @default false
             */
            enable_streaming: boolean | null;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Task Id */
            task_id?: string | null;
            /** Status */
            status: string;
            /** User Input Request */
            user_input_request?: Record<string, never> | null;
        };
        /** StatusRecordDetail */
        StatusRecordDetail: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Actor */
            actor?: string | null;
            /** Note */
            note?: string | null;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Request */
            request: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Requesting Actor Id */
            requesting_actor_id?: string | null;
            /** Parent Actor Id */
            parent_actor_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Current Status */
            current_status: string;
            /**
             * Current Status Timestamp
             * Format: date-time
             */
            current_status_timestamp: string;
            /** Current Status Actor */
            current_status_actor?: string | null;
            /** Current Status Note */
            current_status_note?: string | null;
            /** Timeline */
            timeline?: string | null;
            /** Account */
            account?: string[] | null;
            /** Context */
            context?: Record<string, never> | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageDetail"][];
            /** Status Records */
            status_records: components["schemas"]["StatusRecordDetail"][];
            /** Results */
            results: components["schemas"]["TaskResultDetail"][];
            /** Child Tasks */
            child_tasks: components["schemas"]["TaskSummary"][];
        };
        /** TaskDetailResponse */
        TaskDetailResponse: {
            /** Success */
            success: boolean;
            task: components["schemas"]["TaskDetail"];
        };
        /**
         * TaskEditableResources
         * @description Response model for task editable resources
         */
        TaskEditableResources: {
            /** Task Id */
            task_id: string;
            /** Resources */
            resources: components["schemas"]["EditableResource"][];
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Success */
            success: boolean;
            /** Tasks */
            tasks: components["schemas"]["TaskSummary"][];
            /** Total Count */
            total_count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** TaskResultDetail */
        TaskResultDetail: {
            /** Id */
            id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Result Type */
            result_type: string;
            /** Output */
            output: Record<string, never>;
            /** Success */
            success: boolean;
            /** Error Message */
            error_message?: string | null;
            /** Version */
            version: number;
            /** Account */
            account?: string[] | null;
        };
        /** TaskSummary */
        TaskSummary: {
            /** Id */
            id: string;
            /** Request */
            request: string;
            /** Current Status */
            current_status: string;
            /**
             * Current Status Timestamp
             * Format: date-time
             */
            current_status_timestamp: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Timeline */
            timeline?: string | null;
            /** Account */
            account?: string[] | null;
            /** Context */
            context?: Record<string, never> | null;
            /** Extra Metadata */
            extra_metadata?: Record<string, never> | null;
        };
        /**
         * UpdateMeetingRequest
         * @description Request model for updating a meeting.
         */
        UpdateMeetingRequest: {
            /**
             * Title
             * @description Meeting title
             */
            title?: string | null;
            /**
             * Description
             * @description Meeting description
             */
            description?: string | null;
            /**
             * Start Time
             * @description Meeting start time
             */
            start_time?: string | null;
            /**
             * End Time
             * @description Meeting end time
             */
            end_time?: string | null;
            /**
             * Attendees
             * @description List of attendee names/emails
             */
            attendees?: string[] | null;
            /**
             * Location
             * @description Meeting location
             */
            location?: string | null;
            /**
             * Meeting Url
             * @description Virtual meeting URL
             */
            meeting_url?: string | null;
            /**
             * Status
             * @description Meeting status
             */
            status?: string | null;
            /**
             * Client Meeting
             * @description Whether this is a client meeting
             */
            client_meeting?: boolean | null;
        };
        /**
         * UserInputResponse
         * @description Request model for user input responses.
         */
        UserInputResponse: {
            /**
             * Request Id
             * @description Request ID to respond to
             */
            request_id: string;
            /**
             * Response
             * @description User response
             */
            response: string;
            /**
             * Reason
             * @description Reason for the response
             * @default
             */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    detailed_health_check_api_v1_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    readiness_check_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    liveness_check_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    process_framework_request_framework_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameworkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_options_framework_process_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    respond_to_user_input_framework_user_input_respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInputResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_input_options_framework_user_input_respond_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    send_message_framework_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_options_framework_messages_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_conversation_history_framework_conversations__conversation_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_history_options_framework_conversations__conversation_id__history_options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_conversations_framework_conversations_get: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversations_options_framework_conversations_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    respond_to_conversation_user_input_framework_conversations__conversation_id__user_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInputResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_user_input_options_framework_conversations__conversation_id__user_input_options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_framework_status_framework_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_options_framework_status_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    send_message_api_v1_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_core_agent_api_v1_core_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoreAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreAgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_core_agent_status_api_v1_core_agent_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_conversation_history_api_v1_core_agent_conversation__parent_task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_conversations_api_v1_core_agent_conversations__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_agents__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_tasks_api_v1_tasks__get: {
        parameters: {
            query?: {
                /** @description Page number (starts from 1) */
                page?: number;
                /** @description Number of tasks per page */
                page_size?: number;
                /** @description Filter by task status */
                status_filter?: string | null;
                /** @description Filter by user ID */
                user_id?: string | null;
                /** @description Show only parent tasks (no parent_id) */
                parent_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_detail_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_editable_resources_api_v1_tasks__task_id__editable_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEditableResources"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_editable_resources_api_v1_tasks_editable_resources_get: {
        parameters: {
            query?: {
                /** @description Filter by resource type: email_draft, crm_record, calendar_event */
                resource_type?: string | null;
                /** @description Maximum number of resources to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditableResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_integrations_api_v1_integrations__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    get_integration_status_api_v1_integrations__integration_name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_integration_api_v1_integrations__integration_name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_emails_api_v1_emails__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_calendar_integrations_api_v1_calendar_integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarProvider"][];
                };
            };
        };
    };
    connect_calendar_provider_api_v1_calendar_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_calendar_provider_api_v1_calendar_disconnect__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_calendar_data_api_v1_calendar_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_meetings_api_v1_calendar_meetings_get: {
        parameters: {
            query?: {
                /** @description Filter by start date (YYYY-MM-DD) */
                start_date?: string | null;
                /** @description Filter by end date (YYYY-MM-DD) */
                end_date?: string | null;
                /** @description Filter by calendar provider */
                provider?: string | null;
                /** @description Filter by client meeting flag */
                client_meeting?: boolean | null;
                /** @description Filter by meeting status */
                status?: string | null;
                /** @description Maximum number of meetings to return */
                limit?: number;
                /** @description Number of meetings to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_v1_calendar_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_v1_calendar_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_api_v1_calendar_meetings__meeting_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_v1_calendar_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_recap_api_v1_calendar_meetings__meeting_id__recap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRecap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_recap_status_api_v1_calendar_meetings__meeting_id__recap_patch: {
        parameters: {
            query: {
                has_recap: boolean;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_workflows_api_v1_workflows__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_analytics_api_v1_analytics__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    api_info_api_v1_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
