# generated by datamodel-codegen:
#   filename:  1099consolidated_extract.json
#   timestamp: 2025-09-22T20:02:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Payer(BaseModel):
    name: str = Field(..., description="Payer's full name")
    federal_id: str = Field(..., description="Payer's federal ID number")
    address: str = Field(..., description="Payer's address")
    phone: str = Field(..., description="Payer's contact phone number")


class Recipient(BaseModel):
    name: str = Field(..., description="Recipient's full name")
    taxpayer_id: str = Field(..., description="Recipient's taxpayer ID")
    address: str = Field(..., description="Recipient's address")
    account_number: str = Field(..., description="Recipient's account number")


class Field1099DIV(BaseModel):
    field_1a_total_ordinary_dividends: float = Field(
        ..., alias='1a_total_ordinary_dividends', description='Total ordinary dividends'
    )
    field_1b_qualified_dividends: float = Field(
        ..., alias='1b_qualified_dividends', description='Qualified dividends'
    )
    field_2a_total_capital_gain_distributions: float = Field(
        ...,
        alias='2a_total_capital_gain_distributions',
        description='Total capital gain distributions',
    )
    field_2b_unrecaptured_sec1250_gain: float = Field(
        ...,
        alias='2b_unrecaptured_sec1250_gain',
        description='Unrecaptured Section 1250 gain',
    )
    field_2c_section1202_gain: float = Field(
        ..., alias='2c_section1202_gain', description='Section 1202 gain'
    )
    field_2d_collectibles_28pct_gain: float = Field(
        ..., alias='2d_collectibles_28pct_gain', description='Collectibles 28% gain'
    )
    field_3_nondividend_distributions: float = Field(
        ...,
        alias='3_nondividend_distributions',
        description='Nondividend distributions',
    )
    field_4_federal_income_tax_withheld: float = Field(
        ...,
        alias='4_federal_income_tax_withheld',
        description='Federal income tax withheld',
    )
    field_5_section_199A_dividends: float = Field(
        ..., alias='5_section_199A_dividends', description='Section 199A dividends'
    )
    field_6_investment_expenses: float = Field(
        ..., alias='6_investment_expenses', description='Investment expenses'
    )
    field_7_foreign_tax_paid: float = Field(
        ..., alias='7_foreign_tax_paid', description='Foreign tax paid'
    )
    field_8_foreign_country: str = Field(
        ..., alias='8_foreign_country', description='Foreign country name'
    )
    field_9_cash_liquidation_distributions: float = Field(
        ...,
        alias='9_cash_liquidation_distributions',
        description='Cash liquidation distributions',
    )
    field_10_noncash_liquidation_distributions: float = Field(
        ...,
        alias='10_noncash_liquidation_distributions',
        description='Noncash liquidation distributions',
    )
    field_12_exempt_interest_dividends: float = Field(
        ...,
        alias='12_exempt_interest_dividends',
        description='Exempt interest dividends',
    )
    field_13_specified_private_activity_bond_interest: float = Field(
        ...,
        alias='13_specified_private_activity_bond_interest',
        description='Specified private activity bond interest',
    )
    field_14_state: str = Field(..., alias='14_state', description='State name')
    field_15_state_id_number: str = Field(
        ..., alias='15_state_id_number', description='State ID number'
    )
    field_16_state_tax_withheld: float = Field(
        ..., alias='16_state_tax_withheld', description='State tax withheld'
    )


class Field1099INT(BaseModel):
    field_1_interest_income: float = Field(
        ..., alias='1_interest_income', description='Interest income'
    )
    field_3_us_savings_bond_treasury_interest: float = Field(
        ...,
        alias='3_us_savings_bond_treasury_interest',
        description='US savings bond treasury interest',
    )
    field_4_federal_income_tax_withheld: float = Field(
        ...,
        alias='4_federal_income_tax_withheld',
        description='Federal income tax withheld',
    )
    field_5_investment_expenses: float = Field(
        ..., alias='5_investment_expenses', description='Investment expenses'
    )
    field_6_foreign_tax_paid: float = Field(
        ..., alias='6_foreign_tax_paid', description='Foreign tax paid'
    )
    field_7_foreign_country: str = Field(
        ..., alias='7_foreign_country', description='Foreign country name'
    )
    field_8_tax_exempt_interest: float = Field(
        ..., alias='8_tax_exempt_interest', description='Tax-exempt interest'
    )
    field_9_private_activity_bond_interest: float = Field(
        ...,
        alias='9_private_activity_bond_interest',
        description='Private activity bond interest',
    )
    field_10_market_discount: float = Field(
        ..., alias='10_market_discount', description='Market discount'
    )
    field_11_bond_premium: float = Field(
        ..., alias='11_bond_premium', description='Bond premium'
    )
    field_12_bond_premium_treasury: float = Field(
        ..., alias='12_bond_premium_treasury', description='Bond premium treasury'
    )
    field_13_bond_premium_tax_exempt: float = Field(
        ..., alias='13_bond_premium_tax_exempt', description='Bond premium tax-exempt'
    )
    field_14_tax_exempt_cusip: str = Field(
        ..., alias='14_tax_exempt_cusip', description='Tax-exempt CUSIP'
    )
    field_15_state: str = Field(..., alias='15_state', description='State name')
    field_16_state_id_number: str = Field(
        ..., alias='16_state_id_number', description='State ID number'
    )
    field_17_state_tax_withheld: float = Field(
        ..., alias='17_state_tax_withheld', description='State tax withheld'
    )


class ShortTerm(BaseModel):
    proceeds: float = Field(..., description='Proceeds from transactions')
    cost_basis: float = Field(..., description='Cost basis of transactions')
    gain_loss: float = Field(..., description='Gain or loss from transactions')
    federal_tax_withheld: float = Field(..., description='Federal tax withheld')
    state: str = Field(..., description='State name')
    state_id_number: str = Field(..., description='State ID number')
    state_tax_withheld: float = Field(..., description='State tax withheld')


class LongTerm(BaseModel):
    proceeds: float = Field(..., description='Proceeds from transactions')
    cost_basis: float = Field(..., description='Cost basis of transactions')
    gain_loss: float = Field(..., description='Gain or loss from transactions')
    federal_tax_withheld: float = Field(..., description='Federal tax withheld')
    state: str = Field(..., description='State name')
    state_id_number: str = Field(..., description='State ID number')
    state_tax_withheld: float = Field(..., description='State tax withheld')


class Field1099B(BaseModel):
    short_term: ShortTerm = Field(..., description='Short-term transactions')
    long_term: LongTerm = Field(..., description='Long-term transactions')


class Field1099MISC(BaseModel):
    field_1_rents: float = Field(..., alias='1_rents', description='Rents received')
    field_2_royalties: float = Field(
        ..., alias='2_royalties', description='Royalties received'
    )
    field_3_other_income: float = Field(
        ..., alias='3_other_income', description='Other income received'
    )
    field_4_federal_income_tax_withheld: float = Field(
        ...,
        alias='4_federal_income_tax_withheld',
        description='Federal income tax withheld',
    )
    field_5_fishing_boat_proceeds: float = Field(
        ..., alias='5_fishing_boat_proceeds', description='Fishing boat proceeds'
    )
    field_6_medical_and_healthcare_payments: float = Field(
        ...,
        alias='6_medical_and_healthcare_payments',
        description='Medical and healthcare payments',
    )
    field_7_nonemployee_compensation: float = Field(
        ..., alias='7_nonemployee_compensation', description='Nonemployee compensation'
    )
    field_8_substitute_payments_in_lieu: float = Field(
        ...,
        alias='8_substitute_payments_in_lieu',
        description='Substitute payments in lieu',
    )
    field_9_crop_insurance_proceeds: float = Field(
        ..., alias='9_crop_insurance_proceeds', description='Crop insurance proceeds'
    )
    field_10_gross_proceeds_to_attorney: float = Field(
        ...,
        alias='10_gross_proceeds_to_attorney',
        description='Gross proceeds to attorney',
    )
    field_12_section409A_income: float = Field(
        ..., alias='12_section409A_income', description='Section 409A income'
    )
    field_14_nonqualified_deferred_comp: float = Field(
        ...,
        alias='14_nonqualified_deferred_comp',
        description='Nonqualified deferred compensation',
    )
    field_15_state: str = Field(..., alias='15_state', description='State name')
    field_16_state_id_number: str = Field(
        ..., alias='16_state_id_number', description='State ID number'
    )
    field_17_state_tax_withheld: float = Field(
        ..., alias='17_state_tax_withheld', description='State tax withheld'
    )


class Field1099OID(BaseModel):
    field_1_original_issue_discount: float = Field(
        ..., alias='1_original_issue_discount', description='Original issue discount'
    )
    field_2_other_periodic_interest: float = Field(
        ..., alias='2_other_periodic_interest', description='Other periodic interest'
    )
    field_3_early_withdrawal_penalty: float = Field(
        ..., alias='3_early_withdrawal_penalty', description='Early withdrawal penalty'
    )
    field_4_federal_income_tax_withheld: float = Field(
        ...,
        alias='4_federal_income_tax_withheld',
        description='Federal income tax withheld',
    )
    field_5_market_discount: float = Field(
        ..., alias='5_market_discount', description='Market discount'
    )
    field_6_acquisition_premium: float = Field(
        ..., alias='6_acquisition_premium', description='Acquisition premium'
    )
    field_7_description: str = Field(
        ..., alias='7_description', description='Description of the item'
    )
    field_8_original_issue_discount_on_us_treasury: float = Field(
        ...,
        alias='8_original_issue_discount_on_us_treasury',
        description='OID on US Treasury',
    )
    field_9_investment_expenses: float = Field(
        ..., alias='9_investment_expenses', description='Investment expenses'
    )
    field_10_bond_premium: float = Field(
        ..., alias='10_bond_premium', description='Bond premium'
    )
    field_11_tax_exempt_oid: float = Field(
        ..., alias='11_tax_exempt_oid', description='Tax-exempt OID'
    )
    field_12_state: str = Field(..., alias='12_state', description='State name')
    field_13_state_id_number: str = Field(
        ..., alias='13_state_id_number', description='State ID number'
    )
    field_14_state_tax_withheld: float = Field(
        ..., alias='14_state_tax_withheld', description='State tax withheld'
    )


class Forms(BaseModel):
    field_1099_DIV: Field1099DIV = Field(
        ..., alias='1099-DIV', description='1099-DIV form details'
    )
    field_1099_INT: Field1099INT = Field(
        ..., alias='1099-INT', description='1099-INT form details'
    )
    field_1099_B: Field1099B = Field(
        ..., alias='1099-B', description='1099-B form details'
    )
    field_1099_MISC: Field1099MISC = Field(
        ..., alias='1099-MISC', description='1099-MISC form details'
    )
    field_1099_OID: Field1099OID = Field(
        ..., alias='1099-OID', description='1099-OID form details'
    )


class Model(BaseModel):
    payer: Payer = Field(..., description='Payer information')
    recipient: Recipient = Field(..., description='Recipient information')
    forms: Forms = Field(..., description='Tax forms information')
