# generated by datamodel-codegen:
#   filename:  k1_extract.json
#   timestamp: 2025-09-22T20:02:18+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict

from pydantic import BaseModel, Field


class Partnership(BaseModel):
    ein: str = Field(
        ..., description='Employer Identification Number, format: XX-XXXXXXX'
    )
    name: str = Field(..., description='Name of the partnership')
    address: str = Field(..., description='Address of the partnership')


class Type(Enum):
    Individual = 'Individual'
    Entity = 'Entity'


class ProfitPct(BaseModel):
    begin: float = Field(..., description='Beginning profit percentage')
    end: float = Field(..., description='Ending profit percentage')


class LossPct(BaseModel):
    begin: float = Field(..., description='Beginning loss percentage')
    end: float = Field(..., description='Ending loss percentage')


class CapitalPct(BaseModel):
    begin: float = Field(..., description='Beginning capital percentage')
    end: float = Field(..., description='Ending capital percentage')


class CapitalAccount(BaseModel):
    beginning: float = Field(..., description='Beginning capital account balance')
    currentYearIncomeLoss: float = Field(..., description='Current year income or loss')
    withdrawalsDistributions: float = Field(
        ..., description='Withdrawals or distributions amount'
    )
    ending: float = Field(..., description='Ending capital account balance')


class Partner(BaseModel):
    ssnTin: str = Field(
        ...,
        description='Social Security or Tax Identification Number, masked format: ***-**-XXXX',
    )
    name: str = Field(..., description='Name of the partner')
    address: str = Field(..., description='Address of the partner')
    type: Type = Field(..., description='Type of partner')
    partnerRole: str = Field(..., description='Role of the partner in the partnership')
    profitPct: ProfitPct = Field(..., description='Profit percentage details')
    lossPct: LossPct = Field(..., description='Loss percentage details')
    capitalPct: CapitalPct = Field(..., description='Capital percentage details')
    capitalAccount: CapitalAccount = Field(..., description='Capital account details')


class OtherIncome(BaseModel):
    stakingIncome: float = Field(..., description='Staking income amount')


class OtherDeductions(BaseModel):
    portfolioDeductions: float = Field(..., description='Portfolio deductions amount')


class K1Boxes(BaseModel):
    ordinaryBusinessIncomeLoss: float = Field(
        ..., description='Ordinary business income or loss'
    )
    interestIncome: float = Field(..., description='Interest income amount')
    netLongTermCapitalGain: float = Field(..., description='Net long-term capital gain')
    otherIncome: OtherIncome = Field(..., description='Other income details')
    otherDeductions: OtherDeductions = Field(
        ..., description='Other deductions details'
    )
    selfEmploymentIncomeLoss: float = Field(
        ..., description='Self-employment income or loss'
    )
    taxExemptIncome: float = Field(..., description='Tax-exempt income amount')
    distributions: float = Field(..., description='Distributions amount')
    otherInformation: Dict[str, Any] = Field(
        ..., description='Other information details'
    )
    foreignTaxesPaid: float = Field(..., description='Foreign taxes paid amount')


class ForeignIncome(BaseModel):
    longTermCapitalGain: float = Field(
        ..., description='Long-term capital gain from foreign income'
    )
    otherIncomeStaking: float = Field(..., description='Other income from staking')


class Deductions(BaseModel):
    portfolioDeductions: float = Field(..., description='Portfolio deductions amount')


class ScheduleK3(BaseModel):
    foreignIncome: ForeignIncome = Field(..., description='Foreign income details')
    deductions: Deductions = Field(..., description='Deductions details')


class Footnotes(BaseModel):
    portfolioIncomeTreatment: bool = Field(
        ..., description='Indicates if portfolio income is treated'
    )
    subjectToNiit: bool = Field(
        ..., description='Indicates if subject to Net Investment Income Tax'
    )
    ubtiGenerated: bool = Field(
        ..., description='Indicates if Unrelated Business Taxable Income is generated'
    )


class Model(BaseModel):
    partnership: Partnership = Field(
        ..., description='Details of the partnership entity'
    )
    partner: Partner = Field(..., description='Details of the partner')
    k1Boxes: K1Boxes = Field(..., description='K-1 form box details')
    scheduleK3: ScheduleK3 = Field(..., description='Schedule K-3 details')
    footnotes: Footnotes = Field(
        ..., description='Footnotes related to the partnership'
    )
