# generated by datamodel-codegen:
#   filename:  w2_extract.json
#   timestamp: 2025-09-22T20:02:19+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Employer(BaseModel):
    employerIdentificationNumber: str = Field(
        ..., description='Employer Identification Number (EIN)'
    )
    employerName: str = Field(..., description="Employer's name")
    employerAddress: str = Field(..., description="Employer's address")


class Employee(BaseModel):
    socialSecurityNumber: str = Field(
        ..., description="Employee's Social Security Number (SSN)"
    )
    employeeName: str = Field(..., description="Employee's name")
    employeeAddress: str = Field(..., description="Employee's address")


class FederalBoxes(BaseModel):
    wagesTipsOtherCompensation: float = Field(..., description='box 1')
    federalIncomeTaxWithheld: float = Field(..., description='box 2')
    socialSecurityWages: float = Field(..., description='box 3, watch anchor')
    socialSecurityTaxWithheld: float = Field(..., description='box 4')
    medicareWagesAndTips: float = Field(..., description='box 5, watch anchor')
    medicareTaxWithheld: float = Field(..., description='box 6')
    socialSecurityTips: float = Field(..., description='box 7, watch anchor')
    allocatedTips: float = Field(..., description='box 8')
    dependentCareBenefits: float = Field(..., description='box 10')
    nonqualifiedPlans: float = Field(..., description='box 11')


class Box12Codes(BaseModel):
    code12a: str = Field(..., description='Code for box 12a')
    code12c: str = Field(..., description='Code for box 12c')
    amount12a: float = Field(..., description='Amount for box 12a')
    amount12b: float = Field(..., description='Amount for box 12b')
    amount12c: float = Field(..., description='Amount for box 12c')
    amount12d: float = Field(..., description='Amount for box 12d')


class Box13Checkboxes(BaseModel):
    statutoryEmployee: bool = Field(..., description='1st box in a row')
    retirementPlan: bool = Field(..., description='2nd box in a row')
    thirdPartySickPay: bool = Field(..., description='3rd box in a row')


class State(BaseModel):
    state: str = Field(..., description='State abbreviation')
    employerStateId: str = Field(..., description='Employer state ID number')
    stateWages: float = Field(..., description='State wages amount')
    stateIncomeTax: float = Field(..., description='State income tax amount')


class Locality(BaseModel):
    localityName: str = Field(..., description='Locality name')
    localWages: float = Field(..., description='Local wages amount')
    localIncomeTax: float = Field(..., description='Local income tax amount')


class Model(BaseModel):
    taxYear: float = Field(..., description='Tax year, e.g., 2010')
    reissuedStatement: bool = Field(
        ..., description='Indicates if statement is reissued'
    )
    controlNumber: str = Field(..., description='Control number for the form')
    employer: Employer = Field(..., description='Employer details')
    employee: Employee = Field(..., description='Employee details')
    federalBoxes: FederalBoxes = Field(..., description='Federal tax details')
    box12Codes: Box12Codes = Field(..., description='Box 12 codes and amounts')
    box13Checkboxes: Box13Checkboxes = Field(..., description='Box 13 checkboxes')
    states: List[State] = Field(..., description='State tax details')
    localities: List[Locality] = Field(..., description='Local tax details')
