"""add_quickbooks_service_type

Revision ID: 6494c8500fa5
Revises: 52f90a26dd50
Create Date: 2025-08-21 21:59:22.602083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6494c8500fa5'
down_revision = '52f90a26dd50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add QUICKBOOKS to the servicetypeenum
    op.execute("ALTER TYPE servicetypeenum ADD VALUE 'QUICKBOOKS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type if rollback is needed
    pass
    # ### end Alembic commands ### 