"""add conversation

Revision ID: 8b96ad10d015
Revises: f8a12f995629
Create Date: 2025-07-31 11:40:25.735937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b96ad10d015'
down_revision = 'f8a12f995629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.drop_constraint('messages_task_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'task_id')
    op.add_column('tasks', sa.Column('message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'message_id')
    op.add_column('messages', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_task_id_fkey', 'messages', 'tasks', ['task_id'], ['id'])
    op.drop_column('messages', 'conversation_id')
    op.drop_table('conversations')
    # ### end Alembic commands ### 