# generated by datamodel-codegen:
#   filename:  int1099.json
#   timestamp: 2025-09-22T20:02:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Address(BaseModel):
    street: str
    city: str
    state: constr(max_length=2)
    zipCode: str


class Payer(BaseModel):
    tin: constr(pattern=r'^\d{2}-\d{7}$|^\d{3}-\d{2}-\d{4}$') = Field(
        ..., description="Payer's TIN (EIN format XX-XXXXXXX or SSN format XXX-XX-XXXX)"
    )
    name: str = Field(..., description="Payer's name")
    address: Address
    phoneNumber: Optional[str] = Field(None, description="Payer's telephone number")


class Address1(BaseModel):
    street: str
    city: str
    state: Optional[constr(max_length=2)] = None
    zipCode: Optional[str] = None
    foreignCountry: Optional[str] = None


class Recipient(BaseModel):
    tin: constr(pattern=r'^\d{3}-\d{2}-\d{4}$|^\d{2}-\d{7}$') = Field(
        ...,
        description="Recipient's TIN (SSN format XXX-XX-XXXX or EIN format XX-XXXXXXX)",
    )
    name: str = Field(..., description="Recipient's name")
    address: Address1


class Interest(BaseModel):
    interestIncome: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 1: Interest income'
    )
    earlyWithdrawalPenalty: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 2: Early withdrawal penalty'
    )
    interestOnUSSavingsBondsAndTreasuryObligations: Optional[
        confloat(ge=0.0, multiple_of=0.01)
    ] = Field(
        None,
        description='Box 3: Interest on U.S. Savings Bonds and Treasury obligations',
    )
    federalIncomeTaxWithheld: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 4: Federal income tax withheld'
    )
    investmentExpenses: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 5: Investment expenses'
    )
    foreignTaxPaid: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 6: Foreign tax paid'
    )
    foreignCountryOrPossession: Optional[str] = Field(
        None, description='Box 7: Foreign country or U.S. possession'
    )
    taxExemptInterest: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 8: Tax-exempt interest'
    )
    specifiedPrivateActivityBondInterest: Optional[
        confloat(ge=0.0, multiple_of=0.01)
    ] = Field(None, description='Box 9: Specified private activity bond interest')
    marketDiscount: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 10: Market discount'
    )
    bondPremium: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 11: Bond premium'
    )
    bondPremiumOnTreasuryObligations: Optional[confloat(ge=0.0, multiple_of=0.01)] = (
        Field(None, description='Box 12: Bond premium on Treasury obligations')
    )
    bondPremiumOnTaxExemptBond: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Box 13: Bond premium on tax-exempt bond'
    )


class StateItem(BaseModel):
    stateNumber: conint(ge=1, le=99) = Field(
        ..., description='State identification number'
    )
    stateAbbreviation: constr(max_length=2) = Field(
        ..., description='State abbreviation'
    )
    payerStateNumber: Optional[str] = Field(
        None, description="Payer's state identification number"
    )
    stateTaxWithheld: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='State tax withheld'
    )
    stateIncome: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='State income'
    )


class AdditionalInformation(BaseModel):
    corrected: Optional[bool] = Field(
        None, description='Check if this is a corrected form'
    )
    void: Optional[bool] = Field(None, description='Check if this form is void')
    fatca: Optional[bool] = Field(None, description='FATCA filing requirement')
    secondTinNotification: Optional[bool] = Field(
        None, description='2nd TIN notification'
    )
    directSalesIndicator: Optional[constr(max_length=1)] = Field(
        None, description='Direct sales indicator (if applicable)'
    )
    notes: Optional[str] = Field(None, description='Additional notes or comments')


class TaxForm1099Int(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taxYear: conint(ge=1900, le=9999) = Field(
        ..., description='Tax year for this 1099-INT'
    )
    payer: Payer
    recipient: Recipient
    accountNumber: Optional[str] = Field(
        None, description='Account number (if required by payer)'
    )
    interest: Interest
    state: Optional[List[StateItem]] = Field(
        None, description='State tax information (up to 2 states)', max_length=2
    )
    additionalInformation: Optional[AdditionalInformation] = None
    cusip: Optional[constr(pattern=r'^[0-9A-Z]{9}$')] = Field(
        None, description='CUSIP number for the security (if applicable)'
    )
