# generated by datamodel-codegen:
#   filename:  k1.json
#   timestamp: 2025-09-22T20:02:15+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class FormType(Enum):
    field_1065 = '1065'
    field_1120S = '1120S'
    field_1041 = '1041'


class Address(BaseModel):
    street: str
    city: str
    state: Optional[constr(max_length=2)] = None
    zipCode: Optional[str] = None
    foreignCountry: Optional[str] = None


class Entity(BaseModel):
    ein: constr(pattern=r'^\d{2}-\d{7}$') = Field(
        ..., description="Entity's Employer Identification Number"
    )
    name: str = Field(..., description='Name of entity')
    address: Address
    publiclyTraded: Optional[bool] = None
    irsCenter: Optional[str] = None


class PartnerType(Enum):
    general = 'general'
    limited = 'limited'
    limited_liability = 'limited_liability'


class EntityType(Enum):
    individual = 'individual'
    corporation = 'corporation'
    partnership = 'partnership'
    exempt_organization = 'exempt_organization'
    estate_trust = 'estate_trust'
    retirement_plan = 'retirement_plan'


class Partner(BaseModel):
    ssn: constr(pattern=r'^\d{3}-\d{2}-\d{4}$|^\d{2}-\d{7}$') = Field(
        ..., description="Partner's SSN or EIN"
    )
    name: str = Field(..., description="Partner's name")
    address: Address
    partnerType: Optional[PartnerType] = Field(None, description='What type of partner')
    domestic: Optional[bool] = None
    entityType: Optional[EntityType] = Field(
        None, description='If partner is an entity, what type'
    )


class Ownership(BaseModel):
    profitSharingPercentage: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None, description="Partner's share of profit sharing %"
    )
    lossSharingPercentage: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None, description="Partner's share of loss sharing %"
    )
    capitalSharingPercentage: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None, description="Partner's share of capital sharing %"
    )
    beginningCapitalAccount: Optional[float] = Field(
        None, description='Beginning of year capital account'
    )
    endingCapitalAccount: Optional[float] = Field(
        None, description='End of year capital account'
    )


class OrdinaryBusinessIncome(BaseModel):
    ordinaryBusinessIncomeOrLoss: Optional[float] = Field(
        None, description='Box 1: Ordinary business income (loss)'
    )
    netRentalRealEstateIncomeOrLoss: Optional[float] = Field(
        None, description='Box 2: Net rental real estate income (loss)'
    )
    otherNetRentalIncomeOrLoss: Optional[float] = Field(
        None, description='Box 3: Other net rental income (loss)'
    )
    guaranteedPaymentsForServices: Optional[float] = Field(
        None, description='Box 4a: Guaranteed payments for services'
    )
    guaranteedPaymentsForCapital: Optional[float] = Field(
        None, description='Box 4b: Guaranteed payments for capital'
    )
    guaranteedPaymentsForOther: Optional[float] = Field(
        None, description='Box 4c: Guaranteed payments for other'
    )
    interestIncome: Optional[float] = Field(None, description='Box 5: Interest income')
    dividendsQualified: Optional[float] = Field(
        None, description='Box 6a: Qualified dividends'
    )
    dividendsOrdinary: Optional[float] = Field(
        None, description='Box 6b: Ordinary dividends'
    )
    royalties: Optional[float] = Field(None, description='Box 7: Royalties')
    netShortTermCapitalGainOrLoss: Optional[float] = Field(
        None, description='Box 8: Net short-term capital gain (loss)'
    )
    netLongTermCapitalGainOrLoss: Optional[float] = Field(
        None, description='Box 9a: Net long-term capital gain (loss)'
    )
    collectiblesGain: Optional[float] = Field(
        None, description='Box 9b: Collectibles (28%) gain (loss)'
    )
    unrecaptured1250Gain: Optional[float] = Field(
        None, description='Box 9c: Unrecaptured section 1250 gain'
    )
    netSection1231GainOrLoss: Optional[float] = Field(
        None, description='Box 10: Net section 1231 gain (loss)'
    )


class Section179DeductionInformation(BaseModel):
    code: Optional[str] = None
    amount: Optional[float] = None


class OtherDeduction(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None


class OtherInformation(BaseModel):
    section179DeductionInformation: Optional[List[Section179DeductionInformation]] = (
        Field(None, description='Box 11: Section 179 deduction')
    )
    otherDeductions: Optional[List[OtherDeduction]] = Field(
        None, description='Box 12: Other deductions'
    )


class CreditRecaptureItem(BaseModel):
    code: Optional[str] = None
    amount: Optional[float] = None


class ForeignTransaction(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None


class AlternativeMinimumTaxItem(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None


class ItemsAffectingShareholderBasi(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None


class OtherInformation1(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    amount: Optional[float] = None


class Credits(BaseModel):
    creditRecapture: Optional[List[CreditRecaptureItem]] = Field(
        None, description='Box 13: Credits'
    )
    foreignTransactions: Optional[List[ForeignTransaction]] = Field(
        None, description='Box 14: Foreign transactions'
    )
    alternativeMinimumTax: Optional[List[AlternativeMinimumTaxItem]] = Field(
        None, description='Box 15: Alternative minimum tax (AMT) items'
    )
    itemsAffectingShareholderBasis: Optional[List[ItemsAffectingShareholderBasi]] = (
        Field(None, description='Box 16: Items affecting shareholder basis')
    )
    otherInformation: Optional[List[OtherInformation1]] = Field(
        None, description='Box 17: Other information'
    )


class MoreInformation(BaseModel):
    distributions: Optional[float] = Field(None, description='Box 19: Distributions')
    otherInformation: Optional[List[OtherInformation1]] = Field(
        None, description='Box 20: Other information'
    )


class SelfEmploymentEarnings(BaseModel):
    netEarningsFromSelfEmployment: Optional[float] = Field(
        None, description='Net earnings (loss) from self-employment'
    )
    grossFarmingOrFishingIncome: Optional[float] = Field(
        None, description='Gross farming or fishing income'
    )


class AdditionalInformation(BaseModel):
    corrected: Optional[bool] = None
    amended: Optional[bool] = None
    finalK1: Optional[bool] = None
    scheduleB1: Optional[bool] = None
    notes: Optional[str] = None


class TaxFormScheduleK1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taxYear: conint(ge=1900, le=9999) = Field(
        ..., description='Tax year for this Schedule K-1'
    )
    formType: FormType = Field(
        ...,
        description='Type of K-1: 1065 (Partnership), 1120S (S Corporation), or 1041 (Estate/Trust)',
    )
    entity: Entity
    partner: Partner
    ownership: Optional[Ownership] = None
    ordinaryBusinessIncome: Optional[OrdinaryBusinessIncome] = None
    otherInformation: Optional[OtherInformation] = None
    credits: Optional[Credits] = None
    moreInformation: Optional[MoreInformation] = None
    selfEmploymentEarnings: Optional[SelfEmploymentEarnings] = None
    additionalInformation: Optional[AdditionalInformation] = None
