# generated by datamodel-codegen:
#   filename:  w2.json
#   timestamp: 2025-09-22T20:02:17+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Address(BaseModel):
    street: str
    city: str
    state: constr(max_length=2)
    zipCode: str


class Employer(BaseModel):
    ein: constr(pattern=r'^\d{2}-\d{7}$') = Field(
        ..., description='Employer Identification Number (XX-XXXXXXX format)'
    )
    name: str = Field(..., description='Employer name, address, and ZIP code')
    address: Address


class Employee(BaseModel):
    ssn: constr(pattern=r'^\d{3}-\d{2}-\d{4}$') = Field(
        ..., description='Employee Social Security Number (XXX-XX-XXXX format)'
    )
    firstName: str
    middleName: Optional[str] = None
    lastName: str
    suffix: Optional[str] = None
    address: Address


class Wages(BaseModel):
    wagesAndTips: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 1: Wages, tips, other compensation'
    )
    federalIncomeTaxWithheld: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 2: Federal income tax withheld'
    )
    socialSecurityWages: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 3: Social security wages'
    )
    socialSecurityTaxWithheld: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 4: Social security tax withheld'
    )
    medicareWages: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 5: Medicare wages and tips'
    )
    medicareTaxWithheld: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 6: Medicare tax withheld'
    )
    socialSecurityTips: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 7: Social security tips'
    )
    allocatedTips: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 8: Allocated tips'
    )
    dependentCareBenefits: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 10: Dependent care benefits'
    )
    nonqualifiedPlans: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 11: Nonqualified plans'
    )


class Box12Item(BaseModel):
    code: constr(max_length=2) = Field(
        ..., description='Two-letter code (A-Z, AA-EE, etc.)'
    )
    amount: confloat(multiple_of=0.01)


class Box13(BaseModel):
    statutoryEmployee: Optional[bool] = None
    retirementPlan: Optional[bool] = None
    thirdPartySickPay: Optional[bool] = None


class Box14Item(BaseModel):
    description: str
    amount: Optional[confloat(multiple_of=0.01)] = None


class Codes(BaseModel):
    box12: Optional[List[Box12Item]] = Field(
        None, description='Box 12: Codes A-D with amounts', max_length=4
    )
    box13: Optional[Box13] = Field(None, description='Box 13: Checkboxes')
    box14: Optional[List[Box14Item]] = Field(
        None, description='Box 14: Other information'
    )


class StateItem(BaseModel):
    stateAbbreviation: constr(max_length=2) = Field(
        ..., description='Box 15: State abbreviation'
    )
    employerStateId: Optional[str] = Field(
        None, description="Box 15: Employer's state ID number"
    )
    stateWages: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 16: State wages, tips, etc.'
    )
    stateIncomeTax: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 17: State income tax'
    )
    localWages: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 18: Local wages, tips, etc.'
    )
    localIncomeTax: Optional[confloat(multiple_of=0.01)] = Field(
        None, description='Box 19: Local income tax'
    )
    localityName: Optional[str] = Field(None, description='Box 20: Locality name')


class AdditionalInformation(BaseModel):
    correctedW2: Optional[bool] = None
    voidW2: Optional[bool] = None
    thirdPartyNotification: Optional[bool] = None
    householdEmployee: Optional[bool] = None
    notes: Optional[str] = None


class TaxFormW2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taxYear: conint(ge=1900, le=9999) = Field(..., description='Tax year for this W2')
    employer: Employer
    employee: Employee
    controlNumber: Optional[str] = Field(
        None, description='Control number (optional employer use)'
    )
    wages: Wages
    codes: Optional[Codes] = None
    state: Optional[List[StateItem]] = Field(
        None,
        description='State and local tax information (up to 2 states)',
        max_length=2,
    )
    additionalInformation: Optional[AdditionalInformation] = None
